// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLc-iAQBc-_N6G_7xweLd6lwY4KyJfULI',
    appId: '1:592926365762:web:161c1601541f67d465b5db',
    messagingSenderId: '592926365762',
    projectId: 'journal-travel-f09f4',
    authDomain: 'journal-travel-f09f4.firebaseapp.com',
    storageBucket: 'journal-travel-f09f4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCImqNcj7_xfyqRaJbYJcrjWB5xQuUVk-4',
    appId: '1:592926365762:android:5afa96ed7195049d65b5db',
    messagingSenderId: '592926365762',
    projectId: 'journal-travel-f09f4',
    storageBucket: 'journal-travel-f09f4.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLc-iAQBc-_N6G_7xweLd6lwY4KyJfULI',
    appId: '1:592926365762:web:4a7565394fe01d9665b5db',
    messagingSenderId: '592926365762',
    projectId: 'journal-travel-f09f4',
    authDomain: 'journal-travel-f09f4.firebaseapp.com',
    storageBucket: 'journal-travel-f09f4.firebasestorage.app',
  );
}
